### ISSUE TITLE
Loss of digits for numeric data?

### ISSUE THREAD

**Issue by pvaneynd** [altaurog/pgcopy#10]
Hi,

I think that I found a problem when handling numeric datatypes.

In my application I need to insert large numbers. If I insert decimal.Decimal('1456312800000000') then this gets corrupted to 14563128 in the database. However inserting decimal.Decimal('1456312800000001')  works.

I narrowed this down to line 75 in copy.py (https://github.com/altaurog/pgcopy/blob/master/pgcopy/copy.py#L75) where the logic is deleting the 0's at the end of the first number without taking this into account anywhere. In fact when I remove lines 75-78 pgcopy is sending the correct number across.

I'm however far from certain that this is correct as I don't understand the transformation logic fully.

Example with test file:

$ cat test.py
```
import psycopg2
import psycopg2.extras
import decimal
import pgcopy
import os

def records():
    yield (1,
           decimal.Decimal('1456312800000000'))
    yield (2,
           decimal.Decimal('1456312800000001'))


db_host = os.environ['DB_HOST']
db_username = os.environ['DB_USER']
db_password = os.environ['DB_PASSWORD']
db_db = os.environ['DB_DB']

with psycopg2.connect(f"sslmode=disable dbname={db_db} user={db_username} host={db_host} port=5432 password={db_password}") as conn:
        with conn.cursor(
                cursor_factory=psycopg2.extras.NamedTupleCursor) as cur:
                cur.execute("DROP TABLE log_test")
                print(f"deleted table notices: '{conn.notices}' status '{conn.status}'")
                cur.execute(
                    "CREATE TABLE log_test (id INTEGER, time NUMERIC);")
                print(f"created table notices: '{conn.notices}' status '{conn.status}'")
                cols = ['id',
                        'time']
                cm = pgcopy.CopyManager(conn, 'log_test', cols)
                cm.copy(records())
                print(
                    f"added data: '{conn.notices}' status '{conn.status}'")
```

$ python ./test.py
deleted table notices: '[]' status '2'
created table notices: '[]' status '2'
added data: '[]' status '2'
$ psql
psql (9.6.4)
Type "help" for help.

FSM=> select * from log_test;
 id |       time
----+------------------
  1 |         14563128
  2 | 1456312800000001
(2 rows)

Best regards, Peter

**Comment by altaurog** [comment]
Thanks so much for reporting this and for finding the bug!  Removing those lines does solve the problem, but also produces unnecessary data bytes.  The weight needs to be adjusted.

**Comment by altaurog** [comment]
I am preparing a new release

**Comment by pvaneynd** [comment]
Thanks!
Without your library uploading data would be ... slow, so I appreciate the quick turnaround.
