### ISSUE TITLE
Question about array types

### ISSUE THREAD

**Issue by mzpqnxow** [altaurog/pgcopy#15]
Hi, I have a very quick question for you that I wasn't able to answer myself after briefly going through the (tiny) codebase. I assume the answer is 'yes' but is it correct that pgcopy supports arrays of all of the types it supports?

I read the documentation, did a repository wide search for 'array' and did a really fast browse through the code (I've written a similar lib that supports arrays via COPY FROM CSV (it is a total hack, the array part at least, since there shouldn't be **ARRAYS** in CSV columns, but eh, I needed it, and it works he...

Anyway, before I go down the road of throwing away my code, can you confirm that array support is built-in for each type?

Thanks, sorry for the most ignorant issue I have ever entered on github ;)

**Comment by altaurog** [comment]
@mzpqnxow sorry for the delay, just got back from vacation.  I don’t think array types are supported, but that would be an interesting feature to add.

**Comment by altaurog** [comment]
array support added in version 1.4.0

**Comment by mzpqnxow** [comment]
@altaurog Thanks!
