### ISSUE TITLE
"pip install pgcopy" currently fails due to psycopg2 change

### ISSUE THREAD

**Issue by pagreene** [altaurog/pgcopy#18]
`psycopg2` recently removed the pypi entry for `psycopg2`, making it so you need to install via `pip install psycopg2-binary` instead. This means that currently, because `psycopg2` is a dependency of `pgcopy`, pgcopy won't pip install.

**Comment by pagreene** [comment]
Address in https://github.com/altaurog/pgcopy/pull/17

**Comment by altaurog** [comment]
Thanks @pagreene for calling this to my attention.  I hope to come up with a solution for this, but replacing the `"psycopg2"` dependency with `"psycopg2-binary"` isn’t an option, particularly considering that the psycopg2 maintainers recommend installing from source.

I’m sorry I can’t be more help yet, but in lieu of a fix, I might suggest you either:
* prepare your own psycopg2 binary wheel to include in your install
* patch pgcopy’s `setup.py` on the fly before installing

**Comment by altaurog** [comment]
Another approach, [suggested by the psycopg2 maintainer](https://github.com/psycopg/psycopg2/issues/837#issuecomment-481773799), is to specify an earlier version of psycopg2 in your requirements.txt.  This works quite well, assuming you don’t need the latest version:
```
psycopg2==2.7.7
pgcopy
```
