### ISSUE TITLE
Add Time as a Supported DataType

### ISSUE THREAD

**Issue by nathanglover** [altaurog/pgcopy#19]
How hard would it to be add time as a data type? I imagine not too hard because there is already timestamp and date? 

If it is simple I could open a PR, which just need a bit of instruction on where to start. I imagine it would be adding to the `type_formatters` dictionary in copy.py with a formatter method?

**Comment by altaurog** [comment]
@nathanglover yes, that looks right.  A test for the new data types should also be added in `tests/test_datatypes.py`.  I have been meaning to expand the documentation with some instructions for adding data types.  Please do open a PR if you can.  Much appreciated.

**Comment by altaurog** [comment]
I think the postgresql code defining the format for serializing time values is here:
https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/date.c
