### ISSUE TITLE
replace Temp file to StringIO

### ISSUE THREAD

**Issue by koshak01** [altaurog/pgcopy#2]
```
	def copy(self, data):
		datastream = StringIO.StringIO()
		self.writestream(data, datastream)
		datastream.seek(0)
		self.copystream(datastream)
		datastream.close()
```

**Comment by altaurog** [comment]
Did you have a look at the documentation in the readme?  Use of a `StringIO.StringIO` or (recommended) `cStringIO.StringIO` is already supported.  Just pass the constructor as the second parameter to `CopyManager.copy`.
