### ISSUE TITLE
Documentation link broken [latest]

### ISSUE THREAD

**Issue by julsbreakdown** [altaurog/pgcopy#21]
Hello, 
https://pgcopy.readthedocs.io/en/latest/ seems to be broken , https://pgcopy.readthedocs.io/en/1.4.1/ works fine

**Comment by tangyibo** [comment]
Thank you for your help, @julsbreakdown julsbreakdown

**Comment by tangyibo** [comment]
I want to use binary copy command to load data for greenplum/postgresql, pgcopy is the best tool ,I think, But I also want to know , do you have java language version of pgcopy?

**Comment by altaurog** [comment]
Thanks @julsbreakdown for the notification!  I fixed the link, but the 1.4.1 is what you want.  I have updated the link on github accordingly.

**Comment by altaurog** [comment]
@tangyibo no Java version, sorry.
