### ISSUE TITLE
is it posisble merge pgcopy and cpgcopy?

### ISSUE THREAD

**Issue by NewUserHa** [altaurog/pgcopy#23]
is it possible to merge functions of pgcopy and cpgcopy(eg pandas)?

thanks for the good work!

**Comment by altaurog** [comment]
If you just want to load data from a pandas DataFrame into the db, you can use [itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html) with pgcopy:
```python
from datetime import datetime
from pgcopy import CopyManager
import pandas as pd
import psycopg2
cols = ('id', 'timestamp', 'location', 'temperature')
now = datetime.now()
df = pd.DataFrame([
        (0, now, 'Jerusalem', 72.2),
        (1, now, 'New York', 75.6),
        (2, now, 'Moscow', 54.3),
    ],
    columns=cols,
)
conn = psycopg2.connect(database='weather_db')
mgr = CopyManager(conn, 'measurements_table', cols)
mgr.copy(df.itertuples(index=False))

# don't forget to commit!
conn.commit()
```

**Comment by NewUserHa** [comment]
https://github.com/altaurog/cpgcopy/issues/2

thanks for your typing.

I meant `cpgcopy` is not on `pypi`, so it could be great if there's some notes in readme.rst of it.

and can make both `cpgcopy` and `pgcopy` into only one package some like:
```
from pgcopy import pgcopy, cpgcopy
```

again thanks for the good work!

**Comment by altaurog** [comment]
What is the motivation for using cpgcopy?

**Comment by NewUserHa** [comment]
not big motivation, but `about twice as fast.` as you said.

**Comment by altaurog** [comment]
Did you test in your environment?  I also wrote that "Network bandwith and other system limitations are much more likely to be your rate-limiting factor," which is why I don't maintain cpgcopy anymore.

**Comment by NewUserHa** [comment]
I didn't but I saw you wrote that. I was meant `just because you said`.

don't know cpgcopy is not maintained anymore until you told that. wish this info can be added to the readme.rst of cpgcopy.

**Comment by altaurog** [comment]
Thanks, that is a good suggestion.  I have added a note to the cpgcopy readme.
