### ISSUE TITLE
Support for enums?

### ISSUE THREAD

**Issue by nerrons** [altaurog/pgcopy#28]
Hi altaurog,

First of all thanks for this great project. One thing I'm wondering is if pgcopy supports enums (or even better, custom types that are enums). If not, any tips on where I can modify to make it work?

Thanks
nerrons

**Comment by altaurog** [comment]
Nerrons, thanks for asking!  Enums are not supported yet.  It looks like it shouldn’t be too difficult to add enum support, though.

**Comment by altaurog** [comment]
I just released v1.5.0 with enum support.  Please let me know if you need anything else.
