### ISSUE TITLE
Make psycopg2 an optional requirement

### ISSUE THREAD

**Issue by aljosa** [altaurog/pgcopy#32]
Would it be possible to make psycopg2 an optional requirement?

I have a project using psycopg2-binary and (afaik) pgcopy works just fine w/ this installation except that it triggers a psycopg2 source build which is not necessary and also can't be built on the deployment infrastructure (no dev libraries available).

Having it as an optional requirement would allow easy usage for both psycopg2-binary and psycopg2 in deployments.

(note: can't use the recommended approach to pin an older version)

**Comment by altaurog** [comment]
can you install with `pip install --no-dependencies`?

**Comment by aljosa** [comment]
in theory yes but it would break developer experience on the project.
thanks for the suggestion, I'll figure something or possibly include as vendor package in the project.

**Comment by altaurog** [comment]
okay, sorry I can’t be more help, it just doesn’t seem sufficiently compelling

**Comment by sanderbollen-clockworks** [comment]
If using uv, one can override the dependencies by specifying the following in pyproject.toml 

```
[[tool.uv.dependency-metadata]]
name = "pgcopy"
version = "1.6.0"
requires-dist = ["psycopg2-binary", "pytz"]
```
