### ISSUE TITLE
numpy support? - `np.int64`, `np.array`

### ISSUE THREAD

**Issue by SamuelMarks** [altaurog/pgcopy#38]
Feature would be most appreciated :)

EDIT: https://github.com/altaurog/pgcopy/blob/583ee45/pgcopy/copy.py#L337

```py
    def writestream(self, data, datastream):
        datastream.write(BINCOPY_HEADER)
        count = len(self.cols)
        for record in data:
            fmt = [">h"]
            rdat = [count]
            for formatter, val in zip(self.formatters, record):
                if type(val).__module__ == 'numpy':
                    datastream.write(val.tobytes())
                else:
                    f, d = formatter(val)
                    fmt.append(f)
                    rdat.extend(d)
            datastream.write(struct.pack("".join(fmt), *rdat))
        datastream.write(BINCOPY_TRAILER)
```

Something like that anyway. The issue is the `struct.pack` wants the full struct and won't let me just add some bytes in the middle of what it wants to parse/emit. @altaurog any ideas?

**Comment by altaurog** [comment]
is this an np optimization?  or a feature to support np where is isn’t currently supported?

**Comment by SamuelMarks** [comment]
It is a request to add support for `np`; specifically arrays of `np.int64`.

**Comment by altaurog** [comment]
This works for me.
```
CREATE TABLE int_test (
  id serial PRIMARY KEY,
  a int,
  b int
);
```

```
import numpy as np
import psycopg2

from pgcopy import CopyManager

cols = ("id", "a", "b")
records = np.array(
    [
        [1, 2, 3],
        [2, 3, 4],
        [3, 6, 9],
        [4, 10, 100],
    ],
    np.int64,
)

conn = psycopg2.connect(database="pgcopy_test")
mgr = CopyManager(conn, "int_test", cols)
mgr.copy(records)

conn.commit()
```
```
pgcopy_test=> select * from int_test;
 id | a  |  b  
----+----+-----
  1 |  2 |   3
  2 |  3 |   4
  3 |  6 |   9
  4 | 10 | 100
(4 rows)
```

**Comment by altaurog** [comment]
Pandas-specific support isn’t really in scope for this project.  The goal of the project is simply insert performance, not seamless integration with (or optimization for) other libraries.  It seems to work with pandas, but if there are cases where it does not, converting from pandas types to the supported python types is not a difficult step and is unlikely to be a rate-limiting factor in performance.
