### ISSUE TITLE
pd.timedelta support

### ISSUE THREAD

**Issue by filippzorin** [altaurog/pgcopy#39]
Hi, I'd like to have ability to inserting pd.timedelta data into pg tables using pgcopy, as I understand it maps to interval pg dtype. Is there any known issues to implement it?

**Comment by filippzorin** [comment]
I've implemented `timedelta_formatter` which uses pandas.Timedelta
It's not perfect, but works at least for my purpose.
@altaurog, can you take a look, and if you don't mind I create PR in this repo?

```python
def timedelta_formatter(td):
    'get 8 bytes for microseconds, 4 bytes for days and 4 bytes for months'
    if not isinstance(td, pd.Timedelta):
        td = pd.Timedelta(td)
    # For the interval type the format is microseconds as an int64, days as a int32, and months as a int32
    tdc = td.components
    months = 0  # constraint of pandas Timedelta, it doesn't matter sinci pd.Timedelta.max is 106751 days.
    days = tdc.days
    us = (
        tdc.hours * 60 * 60 * 1000 * 1000
        + tdc.minutes * 60 * 1000 * 1000
        + tdc.seconds * 1000 * 1000
        + tdc.milliseconds * 1000
        + tdc.microseconds
    )
    # nanoseconds will be lost since pg interval resolution is 1 microsecond
    return ('iqii', (16, us, days, months))
```

**Comment by altaurog** [comment]
Thanks for your interest in this project, @filippzorin !  I think support for postgresql `interval` is a great idea, but I feel that pandas-specific support is out of scope for this project.  The accepted datatype for this should be python-native `datetime.timedelta`.

**Comment by filippzorin** [comment]
> Thanks for your interest in this project, @filippzorin ! I think support for postgresql `interval` is a great idea, but I feel that pandas-specific support is out of scope for this project. The accepted datatype for this should be python-native `datetime.timedelta`.

agree with you, pandas types are quite specific, but this realization is fit good for my case, so I kept it here if anybody wants to know the approach.
