### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AlvesInfo** [altaurog/pgcopy#5]
mgr = CopyManager(self.cnx, table, champs)
list_rows = [(0, 'Jerusalem'), (1, 'New York'), (2, 'Moscow'),]
mgr.copy(list_rows)

===> error : struct.error: argument for 's' must be a bytes object

**Comment by altaurog** [comment]
`str` in python 3 is a unicode object.  You need to use `bytes` literals or call `encode()` on your strings:

```
list_rows = [(0, b'Jerusalem'), (1, b'New York'), (2, b'Moscow'),]
```
or

```
list_rows = [(0, 'Jerusalem'), (1, 'New York'), (2, 'Moscow'),]
list_rows = [(a, b.encode('utf-8')) for a, b in list_rows]
```
